// <auto-generated />
using System;
using FlightBookingSystem.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightBookingSystem.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlightBookingSystem.DAL.Models.Airport", b =>
                {
                    b.Property<int>("Airport_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Airport_Id"));

                    b.Property<string>("A_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Airport_Id");

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("FlightBookingSystem.DAL.Models.Booking", b =>
                {
                    b.Property<int>("Booking_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Booking_Id"));

                    b.Property<bool>("B_status")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Booking_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Cust_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Reward_Id")
                        .HasColumnType("int");

                    b.Property<int>("Schedule_Id")
                        .HasColumnType("int");

                    b.HasKey("Booking_Id");

                    b.HasIndex("Cust_ID");

                    b.HasIndex("Reward_Id");

                    b.HasIndex("Schedule_Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("FlightBookingSystem.DAL.Models.Customer", b =>
                {
                    b.Property<int>("Customer_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Customer_Id"));

                    b.Property<string>("Aadhar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Phone")
                        .HasColumnType("bigint");

                    b.HasKey("Customer_Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("FlightBookingSystem.DAL.Models.Flight", b =>
                {
                    b.Property<int>("Flight_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Flight_ID"));

                    b.Property<string>("Flight_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Flying_hours")
                        .HasColumnType("int");

                    b.Property<int>("Seat_Capacity")
                        .HasColumnType("int");

                    b.Property<int>("Vacant_Seats")
                        .HasColumnType("int");

                    b.Property<int>("Weight_limit")
                        .HasColumnType("int");

                    b.HasKey("Flight_ID");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("FlightBookingSystem.DAL.Models.Payment", b =>
                {
                    b.Property<int>("Payment_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Payment_Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("Booking_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Customer_Id")
                        .HasColumnType("int");

                    b.Property<bool>("P_status")
                        .HasColumnType("bit");

                    b.Property<string>("P_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Payment_date")
                        .HasColumnType("datetime2");

                    b.HasKey("Payment_Id");

                    b.HasIndex("Booking_Id");

                    b.HasIndex("Customer_Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("FlightBookingSystem.DAL.Models.Reward", b =>
                {
                    b.Property<int>("Reward_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Reward_Id"));

                    b.Property<double>("Discount")
                        .HasColumnType("float");

                    b.Property<int>("loyalty_value")
                        .HasColumnType("int");

                    b.HasKey("Reward_Id");

                    b.ToTable("Rewards");
                });

            modelBuilder.Entity("FlightBookingSystem.DAL.Models.Schedule", b =>
                {
                    b.Property<int>("Schedule_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Schedule_Id"));

                    b.Property<DateTime>("Arr_Time")
                        .HasColumnType("datetime2");

                    b.Property<int>("Arr_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Dep_Time")
                        .HasColumnType("datetime2");

                    b.Property<int>("Dep_id")
                        .HasColumnType("int");

                    b.Property<int?>("Flight_ID")
                        .HasColumnType("int");

                    b.HasKey("Schedule_Id");

                    b.HasIndex("Arr_id");

                    b.HasIndex("Dep_id");

                    b.HasIndex("Flight_ID");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("FlightBookingSystem.DAL.Models.Booking", b =>
                {
                    b.HasOne("FlightBookingSystem.DAL.Models.Customer", "customer")
                        .WithMany("bookings")
                        .HasForeignKey("Cust_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlightBookingSystem.DAL.Models.Reward", null)
                        .WithMany("booking")
                        .HasForeignKey("Reward_Id");

                    b.HasOne("FlightBookingSystem.DAL.Models.Schedule", "schedule")
                        .WithMany()
                        .HasForeignKey("Schedule_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("customer");

                    b.Navigation("schedule");
                });

            modelBuilder.Entity("FlightBookingSystem.DAL.Models.Payment", b =>
                {
                    b.HasOne("FlightBookingSystem.DAL.Models.Booking", "booking")
                        .WithMany("payment")
                        .HasForeignKey("Booking_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlightBookingSystem.DAL.Models.Customer", null)
                        .WithMany("payments")
                        .HasForeignKey("Customer_Id");

                    b.Navigation("booking");
                });

            modelBuilder.Entity("FlightBookingSystem.DAL.Models.Schedule", b =>
                {
                    b.HasOne("FlightBookingSystem.DAL.Models.Airport", "arrivalAirport")
                        .WithMany("arrivalschedule")
                        .HasForeignKey("Arr_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FlightBookingSystem.DAL.Models.Airport", "departureAirport")
                        .WithMany("departureschedule")
                        .HasForeignKey("Dep_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FlightBookingSystem.DAL.Models.Flight", null)
                        .WithMany("schedules")
                        .HasForeignKey("Flight_ID");

                    b.Navigation("arrivalAirport");

                    b.Navigation("departureAirport");
                });

            modelBuilder.Entity("FlightBookingSystem.DAL.Models.Airport", b =>
                {
                    b.Navigation("arrivalschedule");

                    b.Navigation("departureschedule");
                });

            modelBuilder.Entity("FlightBookingSystem.DAL.Models.Booking", b =>
                {
                    b.Navigation("payment");
                });

            modelBuilder.Entity("FlightBookingSystem.DAL.Models.Customer", b =>
                {
                    b.Navigation("bookings");

                    b.Navigation("payments");
                });

            modelBuilder.Entity("FlightBookingSystem.DAL.Models.Flight", b =>
                {
                    b.Navigation("schedules");
                });

            modelBuilder.Entity("FlightBookingSystem.DAL.Models.Reward", b =>
                {
                    b.Navigation("booking");
                });
#pragma warning restore 612, 618
        }
    }
}
